---
title: "Maharjan_He_Final_Project"
author: "Meelisha Maharjan and Xinchen He"
date: "2022-11-24"
output: powerpoint_presentation
---


## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

## Slide with Plot

```{r pressure}
plot(pressure)
```

## Data Collection
Use web-scarping covered in the course. Use R.
```{r}
# install.packages("dataRetrieval")
library(dataRetrieval)
```

```{r}
suppressMessages(library(tidyverse))
library(dataRetrieval)


library(dplyr)
```

```{r}


site_no <- '08324000'
q_code <- '00060'
start <- '2000-01-01'
end <- '2020-12-31'

get_discharge_data <- function(site_no, q_code, start, end) {
  
  url <- paste0('https://waterdata.usgs.gov/nwis/dv?cb_',
        q_code,
        '=on&format=html&site_no=',
        site_no,
        '&legacy=&re[…]module=sw&period=&begin_date=',
          start,
        '&end_date=', 
        end)
  q_data <- readLines(url)
  table_pattern <- '^<tr align="center"><td nowrap="nowrap">'
  q_table <- str_subset(q_data, table_pattern)
 name_exp <- "<tr align=\"center\"><td nowrap=\"nowrap\"> |</span><sup>([A-Z]?)&nbsp;&nbsp;([a-z]?)</sup></td></tr>"

raw_q_data <- str_replace_all(q_table, name_exp, "")

name_exp2 <- " </td><td nowrap=\"nowrap\"><span>"
raw_q_data <- str_replace_all(raw_q_data, name_exp2, " ")
raw_q_data
q_data_list <- str_split_fixed(raw_q_data, " ", n = Inf)
q_timeseries_df <- data.frame(q_data_list)
q_timeseries_df <- q_timeseries_df %>% 
  # rename(
  #   'Date' = 'X1',
  #    'Q_obs' = 'X2'
  #   ) 
# %>%
  mutate(across(c(X2),
              as.numeric)) %>%
  mutate(X1 = as.Date(X1, format = "%m/%d/%Y")
            )
# return(q_timeseries_df)
}
 

q_df <- get_discharge_data(site_no, q_code, start, end)
validate_q <- readNWISdv(siteNumber = site_no, parameterCd = q_code,
  start, end)
library(ggplot2)
# ggplot(data = q_df, aes(Date, Q_obs)) + geom_line()

q_df
```
```{r}
get_drainage_area = function(site_no){
   # Scrape the drainage area
   url2 <- paste0('https://waterdata.usgs.gov/nwis/inventory/?site_no=',
        site_no,
        '&agency_cd=USGS')
   d_data <- readLines(url2)
   d_pattern <- "^.*Drainage area"
   d_line <- str_subset(d_data,d_pattern)
   darea <- unique(unlist(str_extract_all(d_line, "[0-9]*\\.?[0-9]*")))[2]
   darea <- as.numeric(darea)
   return(darea)
}

```

```{r}
tail(validate_q)

```

```{r}
tail(q_df)
```

```{r}

site_no <- '08324000'
q_code <- '00060'
start <- '2019-01-01'
end <- '2020-12-31'
q_all_sites <- data.frame(date = seq(from = as.Date("2019-01-02"), to = as.Date(end), by = 1))

site_df <- read.csv("gauges_Mass.txt", header = FALSE)
site_list <- site_df[,1]

for (site_no in site_list){
  
    
  site_no <- paste0('0',as.character(site_no))
  print(site_no)
  q_df <- try({
    get_discharge_data(site_no, q_code, start, end)
    
  }, silent = TRUE)
  try({
    q_all_sites[site_no] <- q_df$X2
  }, silent = TRUE)
  
}
q_all_sites




```
```{r}
q_all_sites
```


```{r}
# sapply(df, function(x) quantile(x, probs = seq(0, 1, 1/4)))
quantile(x = q_df$Q_obs, probs = c(.05, .5, .95))
```

